apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'is.xyz.mpv'
    compileSdk = 36

    defaultConfig {
        applicationId "is.xyz.mpv"
        minSdkVersion 23
        targetSdk 36
        versionCode 1
        versionName "1.0.0-bridge"
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
